# Automatically generated by Pynguin.
import pytest
import example.lib.ops as module_0


def test_case_0():
    float_0 = 513.127243
    var_0 = module_0.minus(float_0, float_0)
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
