# Automatically generated by Pynguin.
import example.lib.ops as module_0


def test_case_0():
    try:
        str_0 = '"`VzH-,&G\'/LVf:|D\\E'
        int_0 = 2
        var_0 = module_0.plus(str_0, int_0)
    except BaseException:
        pass
